### PR TITLE
chore: support React 17 in peerDependencies

### LINKED ISSUE #7: Support React v17 in peerDependencies
First of all, thank you! This is a great library and alternative to `react-google-login`.

It would be great to have at least basic project maintenance, e.g. upgrading dependencies or making sure that new React versions are supported. In this case, installation with npm 8 is failing due to unsupported React v17. I have to work around it with the legacy peer dependencies flag for now.

### PR DESCRIPTION
**Pull request by mcmxcdev**
## Description

The React v17 announcement post states that there were no breaking changes: https://reactjs.org/blog/2020/10/20/react-v17.html

I can verify this from my experience upgrading other projects from React v16 to v17. Make sure to run this PR locally to verify that everything works as before. 

## Changes
- move `@types/react` from `deps` to `devDeps`
- add missing `@types/react-dom`
- upgrade `react` and `react-dom` to v17
- declare `react` v16 & v17 as allowed in `peerDeps`
- specify `volta` node version that is compatible with npm lockfile v1
- remove `yarn.lock` since npm is in use

Closes https://github.com/mayple/react-google-authorize/issues/7

### CODE REVIEW

**Comment by mhatvan** [comment]
@advance512 can we get this reviewed/merged?

**Comment by mcmxcdev** [comment]
> lgtm

Awesome! I think you will need to do another release for npm too so we can use the new version :)

**Comment by advance512** [comment]
Could you check that it works properly, installing it directly from Github? if all is good, I will release it immediately

**Comment by advance512** [comment]
Also, leave your details to add to the contributors list :)

**Comment by mcmxcdev** [comment]
I ran `npm link` locally, and it looks like all is good when using it on a real-world application ;)

**Pull request merged**
